# Generated by Django 4.2.19 on 2025-03-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fax',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/photos/', verbose_name='Photo de profil'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='absencerequest',
            name='type',
            field=models.CharField(choices=[('Congé payé', 'Congé payé'), ('Congé maladie', 'Congé maladie'), ('Congé sans solde', 'Congé sans solde')], max_length=50),
        ),
    ]
