# Generated by Django 4.2.19 on 2025-04-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_inscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('complaint_type', models.CharField(choices=[('retard', "Retard d'acceptation des demandes"), ('document', 'Problème avec un document'), ('absence', 'Absence non validée'), ('autre', 'Autre')], max_length=20)),
                ('details', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='reclamations/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
