# Generated by Django 4.2.19 on 2025-03-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_fax_user_photo_user_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentrequest',
            old_name='requested_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='document_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Acceptée', 'Acceptée'), ('Rejetée', 'Rejetée')], default='En cours', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
