# Generated by Django 4.2.19 on 2025-04-04 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_reclamation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='authentication.catalogueformation'),
        ),
    ]
