# Generated by Django 4.2.19 on 2025-04-04 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_inscription_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.catalogueformation'),
        ),
    ]
