version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: django_db
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  web:
    build: .
    container_name: django_web
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DB_NAME: django_db
      DB_USER: root
      DB_PASSWORD: ''
      DB_HOST: db
      DB_PORT: 3306
